# Generated by Django 3.0.5 on 2020-11-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='商品名称')),
                ('description', models.TextField(verbose_name='商品详情')),
                ('image', models.CharField(max_length=255, verbose_name='商品封面图片文件路径')),
                ('on_sale', models.IntegerField(verbose_name='商品是否正在售卖')),
                ('sold_count', models.PositiveIntegerField(verbose_name='销量')),
                ('review_count', models.PositiveIntegerField(verbose_name='评价数量')),
                ('rating', models.FloatField(verbose_name='商品平均评分')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SKU 最低价格')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductSkus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='SKU 名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SKU 价格')),
                ('stock', models.PositiveIntegerField(verbose_name='库存')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Products', verbose_name='所属商品 id')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'db_table': 'product_skus',
            },
        ),
    ]
