# Generated by Django 3.0.5 on 2020-11-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '忘记密码',
                'verbose_name_plural': '忘记密码',
                'db_table': 'password_resets',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='用户昵称')),
                ('password', models.CharField(max_length=255, verbose_name='用户密码')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='用户邮箱')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='product.Products', verbose_name='商品ID')),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Users', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户收藏表',
                'verbose_name_plural': '用户收藏表',
                'db_table': 'user_favorite_products',
            },
        ),
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255, verbose_name='省份')),
                ('city', models.CharField(max_length=255, verbose_name='城市')),
                ('district', models.CharField(max_length=255, verbose_name='街道')),
                ('address', models.CharField(max_length=255, verbose_name='具体地址')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='收货人联系方式')),
                ('contact_name', models.CharField(max_length=255, verbose_name='收货人名字')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('zip', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Users', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户地址表',
                'verbose_name_plural': '用户地址表',
                'db_table': 'user_addresses',
            },
        ),
    ]
